# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/karolis/Dev/godot_text_to_speech_gdextension

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/karolis/Dev/godot_text_to_speech_gdextension

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karolis/Dev/godot_text_to_speech_gdextension/CMakeFiles /home/karolis/Dev/godot_text_to_speech_gdextension//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karolis/Dev/godot_text_to_speech_gdextension/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/karolis/Dev/godot_text_to_speech_gdextension/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named godot_text_to_speech

# Build rule for target.
godot_text_to_speech: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 godot_text_to_speech
.PHONY : godot_text_to_speech

# fast build rule for target.
godot_text_to_speech/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/build
.PHONY : godot_text_to_speech/fast

#=============================================================================
# Target rules for targets named generate_bindings

# Build rule for target.
generate_bindings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_bindings
.PHONY : generate_bindings

# fast build rule for target.
generate_bindings/fast:
	$(MAKE) $(MAKESILENT) -f godot-cpp/CMakeFiles/generate_bindings.dir/build.make godot-cpp/CMakeFiles/generate_bindings.dir/build
.PHONY : generate_bindings/fast

#=============================================================================
# Target rules for targets named godot-cpp

# Build rule for target.
godot-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 godot-cpp
.PHONY : godot-cpp

# fast build rule for target.
godot-cpp/fast:
	$(MAKE) $(MAKESILENT) -f godot-cpp/CMakeFiles/godot-cpp.dir/build.make godot-cpp/CMakeFiles/godot-cpp.dir/build
.PHONY : godot-cpp/fast

flite/flite_wrapper.o: flite/flite_wrapper.c.o
.PHONY : flite/flite_wrapper.o

# target to build an object file
flite/flite_wrapper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/flite/flite_wrapper.c.o
.PHONY : flite/flite_wrapper.c.o

flite/flite_wrapper.i: flite/flite_wrapper.c.i
.PHONY : flite/flite_wrapper.i

# target to preprocess a source file
flite/flite_wrapper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/flite/flite_wrapper.c.i
.PHONY : flite/flite_wrapper.c.i

flite/flite_wrapper.s: flite/flite_wrapper.c.s
.PHONY : flite/flite_wrapper.s

# target to generate assembly for a file
flite/flite_wrapper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/flite/flite_wrapper.c.s
.PHONY : flite/flite_wrapper.c.s

src/register_types.o: src/register_types.cpp.o
.PHONY : src/register_types.o

# target to build an object file
src/register_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/src/register_types.cpp.o
.PHONY : src/register_types.cpp.o

src/register_types.i: src/register_types.cpp.i
.PHONY : src/register_types.i

# target to preprocess a source file
src/register_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/src/register_types.cpp.i
.PHONY : src/register_types.cpp.i

src/register_types.s: src/register_types.cpp.s
.PHONY : src/register_types.s

# target to generate assembly for a file
src/register_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/src/register_types.cpp.s
.PHONY : src/register_types.cpp.s

src/text_to_speech.o: src/text_to_speech.cpp.o
.PHONY : src/text_to_speech.o

# target to build an object file
src/text_to_speech.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/src/text_to_speech.cpp.o
.PHONY : src/text_to_speech.cpp.o

src/text_to_speech.i: src/text_to_speech.cpp.i
.PHONY : src/text_to_speech.i

# target to preprocess a source file
src/text_to_speech.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/src/text_to_speech.cpp.i
.PHONY : src/text_to_speech.cpp.i

src/text_to_speech.s: src/text_to_speech.cpp.s
.PHONY : src/text_to_speech.s

# target to generate assembly for a file
src/text_to_speech.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_text_to_speech.dir/build.make CMakeFiles/godot_text_to_speech.dir/src/text_to_speech.cpp.s
.PHONY : src/text_to_speech.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... generate_bindings"
	@echo "... godot-cpp"
	@echo "... godot_text_to_speech"
	@echo "... flite/flite_wrapper.o"
	@echo "... flite/flite_wrapper.i"
	@echo "... flite/flite_wrapper.s"
	@echo "... src/register_types.o"
	@echo "... src/register_types.i"
	@echo "... src/register_types.s"
	@echo "... src/text_to_speech.o"
	@echo "... src/text_to_speech.i"
	@echo "... src/text_to_speech.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/karolis/Dev/godot_text_to_speech_gdextension/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

